In [ ]:
print(__doc__)

import warnings
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
import matplotlib.pyplot as plt
import sklearn.metrics as metric
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn import datasets
from sklearn.exceptions import ConvergenceWarning
 




Automatically created module for IPython interactive environment


In [ ]:
from google.colab import files
uploaded = files.upload() 

Saving data.csv to data.csv


In [ ]:
df = pd.read_csv("data.csv")
df

Make       Model  Year  ... city mpg  Popularity   MSRP
0          BMW  1 Series M  2011  ...       19        3916  46135
1          BMW    1 Series  2011  ...       19        3916  40650
2          BMW    1 Series  2011  ...       20        3916  36350
3          BMW    1 Series  2011  ...       18        3916  29450
4          BMW    1 Series  2011  ...       18        3916  34500
...        ...         ...   ...  ...      ...         ...    ...
11909    Acura         ZDX  2012  ...       16         204  46120
11910    Acura         ZDX  2012  ...       16         204  56670
11911    Acura         ZDX  2012  ...       16         204  50620
11912    Acura         ZDX  2013  ...       16         204  50920
11913  Lincoln      Zephyr  2006  ...       17          61  28995

[11914 rows x 16 columns]

In [ ]:
string_col = ['Make', 'Model', 'Engine Fuel Type', 'Transmission Type', 'Driven_Wheels', 'Market Category', 'Vehicle Size', 'Vehicle Style']
for col in string_col:
    df[col] = df[col].astype('category')
    df[col] = df[col].cat.codes

df

Make  Model  Year  ...  city mpg  Popularity   MSRP
0         4      1  2011  ...        19        3916  46135
1         4      0  2011  ...        19        3916  40650
2         4      0  2011  ...        20        3916  36350
3         4      0  2011  ...        18        3916  29450
4         4      0  2011  ...        18        3916  34500
...     ...    ...   ...  ...       ...         ...    ...
11909     0    901  2012  ...        16         204  46120
11910     0    901  2012  ...        16         204  56670
11911     0    901  2012  ...        16         204  50620
11912     0    901  2013  ...        16         204  50920
11913    25    902  2006  ...        17          61  28995

[11914 rows x 16 columns]

In [ ]:
for col in df.columns:
    df = df[df[col].notnull()]

In [ ]:
df['MSRP'] = pd.qcut(df['MSRP'], 2, labels=['cheap', 'expensive']) # Membagi MSRP antara murah atau mahal, binary
df['MSRP'].replace({'cheap': 0, 'expensive': 1}, inplace=True) # mengubah label jadi angka
df.head()



Make  Model  Year  Engine Fuel Type  ...  highway MPG  city mpg  Popularity  MSRP
0     4      1  2011                 8  ...           26        19        3916     1
1     4      0  2011                 8  ...           28        19        3916     1
2     4      0  2011                 8  ...           28        20        3916     1
3     4      0  2011                 8  ...           28        18        3916     0
4     4      0  2011                 8  ...           28        18        3916     1

[5 rows x 16 columns]

In [ ]:


df.dropna(inplace=True) # Drop missing values
df.describe(include='all')

X, y = df.drop(columns=['MSRP']), df['MSRP'] # Membagi data antara input (X) dan output (y)
X

Make  Model  Year  ...  highway MPG  city mpg  Popularity
0         4      1  2011  ...           26        19        3916
1         4      0  2011  ...           28        19        3916
2         4      0  2011  ...           28        20        3916
3         4      0  2011  ...           28        18        3916
4         4      0  2011  ...           28        18        3916
...     ...    ...   ...  ...          ...       ...         ...
11909     0    901  2012  ...           23        16         204
11910     0    901  2012  ...           23        16         204
11911     0    901  2012  ...           23        16         204
11912     0    901  2013  ...           23        16         204
11913    25    902  2006  ...           26        17          61

[11815 rows x 15 columns]

DATA TRAINING 90&

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

In [125]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), learning_rate_init=0.1, activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [126]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[   0 5314]
 [   0 5319]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      5314
           1       0.50      1.00      0.67      5319

    accuracy                           0.50     10633
   macro avg       0.25      0.50      0.33     10633
weighted avg       0.25      0.50      0.33     10633



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [127]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[  0 594]
 [  0 588]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       594
           1       0.50      1.00      0.66       588

    accuracy                           0.50      1182
   macro avg       0.25      0.50      0.33      1182
weighted avg       0.25      0.50      0.33      1182



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DATA TRAINING 70%

In [132]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [133]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), learning_rate_init=0.1 ,activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [134]:

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[   0 4175]
 [   0 4095]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      4175
           1       0.50      1.00      0.66      4095

    accuracy                           0.50      8270
   macro avg       0.25      0.50      0.33      8270
weighted avg       0.25      0.50      0.33      8270



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [135]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[   0 4175]
 [   0 4095]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      4175
           1       0.50      1.00      0.66      4095

    accuracy                           0.50      8270
   macro avg       0.25      0.50      0.33      8270
weighted avg       0.25      0.50      0.33      8270



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DATA TRAINING 50%

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)

In [141]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', learning_rate_init=0.01, solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [142]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[2984    0]
 [2923    0]]
              precision    recall  f1-score   support

           0       0.51      1.00      0.67      2984
           1       0.00      0.00      0.00      2923

    accuracy                           0.51      5907
   macro avg       0.25      0.50      0.34      5907
weighted avg       0.26      0.51      0.34      5907



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [143]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[2984    0]
 [2923    0]]
              precision    recall  f1-score   support

           0       0.51      1.00      0.67      2984
           1       0.00      0.00      0.00      2923

    accuracy                           0.51      5907
   macro avg       0.25      0.50      0.34      5907
weighted avg       0.26      0.51      0.34      5907



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DATA TRAINING 30%



In [148]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=1)

In [149]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', learning_rate_init=0.1, solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [150]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[1769    0]
 [1775    0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1769
           1       0.00      0.00      0.00      1775

    accuracy                           0.50      3544
   macro avg       0.25      0.50      0.33      3544
weighted avg       0.25      0.50      0.33      3544



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [151]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[1769    0]
 [1775    0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1769
           1       0.00      0.00      0.00      1775

    accuracy                           0.50      3544
   macro avg       0.25      0.50      0.33      3544
weighted avg       0.25      0.50      0.33      3544



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
